when:

  - event: [push, manual]

variables:
  - &repo "misotolar/docker-unbound-builder"
  - &desc "Unbound backport build container"
  - &auth
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD

clone:

  - name: clone
    image: alpine/git
    pull: true
    commands:
      - git init --quiet
      - git remote add origin ${CI_REPO_CLONE_URL}
      - git fetch --quiet --depth=1 origin "+refs/heads/${CI_COMMIT_BRANCH}:"
      - git checkout ${CI_COMMIT_SHA} -b ${CI_COMMIT_BRANCH}

steps:

  - name: version
    image: mwalbeck/determine-docker-tags:0.1
    pull: true
    environment:
      APP_NAME: "BACKPORT"
      CUSTOM_TAGS: "${CI_COMMIT_SHA:0:8},latest"
      VERSION_TYPE: "docker_env"
      INCLUDE_SUFFIX: "no"
      INCLUDE_MAJOR: "no"

  - name: publish
    image: woodpeckerci/plugin-docker-buildx
    pull: true
    settings:
      repo: *repo
      platforms: linux/amd64
      <<: *auth

  - name: package
    image: docker
    pull: true
    environment:
      DOCKER_IMAGE: *repo
      GPG_SIGN_KEY:
        from_secret: GPG_SIGN_KEY
      REPOSITORY_FQDN:
        from_secret: REPOSITORY_FQDN
      REPOSITORY_HOST:
        from_secret: REPOSITORY_HOST
      REPOSITORY_METHOD:
        from_secret: REPOSITORY_METHOD
    commands:
      - rm -rf /tmp/cache/$${DOCKER_IMAGE}
      - docker run --rm --pull=always --add-host=$${REPOSITORY_FQDN}=$${REPOSITORY_HOST} -e GPG_SIGN_KEY="$${GPG_SIGN_KEY}" -e REPOSITORY_FQDN="$${REPOSITORY_FQDN}" -e REPOSITORY_METHOD="$${REPOSITORY_METHOD}" $${DOCKER_IMAGE}
      - docker rmi $${DOCKER_IMAGE}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  - name: update
    image: misotolar/woodpecker-docker-update
    pull: true
    settings:
      repo: *repo
      description: *desc
      readme: README.md
      <<: *auth
